# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='media.proto',
  package='microsoft.azure.media.graph.extensions.grpc',
  syntax='proto3',
  serialized_options=b'\252\002+Microsoft.Azure.Media.Graph.Extensions.Grpc',
  serialized_pb=b'\n\x0bmedia.proto\x12+microsoft.azure.media.graph.extensions.grpc\"\xa5\x01\n\x0fMediaDescriptor\x12\x11\n\ttimescale\x18\x01 \x01(\r\x12h\n\x19video_frame_sample_format\x18\x05 \x01(\x0b\x32\x43.microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormatH\x00\x42\x15\n\x13media_sample_format\"\x89\x04\n\x16VideoFrameSampleFormat\x12^\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32L.microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.Encoding\x12\x65\n\x0cpixel_format\x18\x02 \x01(\x0e\x32O.microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.PixelFormat\x12K\n\ndimensions\x18\x03 \x01(\x0b\x32\x37.microsoft.azure.media.graph.extensions.grpc.Dimensions\x12\x0e\n\x06stride\x18\x04 \x01(\r\".\n\x08\x45ncoding\x12\x07\n\x03\x42MP\x10\x00\x12\x07\n\x03JPG\x10\x01\x12\x07\n\x03PNG\x10\x02\x12\x07\n\x03RAW\x10\x03\"\x9a\x01\n\x0bPixelFormat\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07YUV420P\x10\x14\x12\x0c\n\x08RGB565BE\x10(\x12\x0c\n\x08RGB565LE\x10)\x12\x0c\n\x08RGB555BE\x10*\x12\x0c\n\x08RGB555LE\x10+\x12\t\n\x05RGB24\x10<\x12\t\n\x05\x42GR24\x10=\x12\x08\n\x04\x41RGB\x10P\x12\x08\n\x04RGBA\x10Q\x12\x08\n\x04\x41\x42GR\x10R\x12\x08\n\x04\x42GRA\x10S\"+\n\nDimensions\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\"\x1d\n\x0c\x43ontentBytes\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"@\n\x10\x43ontentReference\x12\x16\n\x0e\x61\x64\x64ress_offset\x18\x01 \x01(\x04\x12\x14\n\x0clength_bytes\x18\x02 \x01(\x04\"$\n\rContentHandle\x12\x13\n\x0bhandle_name\x18\x01 \x01(\tB.\xaa\x02+Microsoft.Azure.Media.Graph.Extensions.Grpcb\x06proto3'
)



_VIDEOFRAMESAMPLEFORMAT_ENCODING = _descriptor.EnumDescriptor(
  name='Encoding',
  full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.Encoding',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BMP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAW', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=547,
  serialized_end=593,
)
_sym_db.RegisterEnumDescriptor(_VIDEOFRAMESAMPLEFORMAT_ENCODING)

_VIDEOFRAMESAMPLEFORMAT_PIXELFORMAT = _descriptor.EnumDescriptor(
  name='PixelFormat',
  full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.PixelFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YUV420P', index=1, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB565BE', index=2, number=40,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB565LE', index=3, number=41,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB555BE', index=4, number=42,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB555LE', index=5, number=43,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB24', index=6, number=60,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR24', index=7, number=61,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARGB', index=8, number=80,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGBA', index=9, number=81,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABGR', index=10, number=82,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGRA', index=11, number=83,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=596,
  serialized_end=750,
)
_sym_db.RegisterEnumDescriptor(_VIDEOFRAMESAMPLEFORMAT_PIXELFORMAT)


_MEDIADESCRIPTOR = _descriptor.Descriptor(
  name='MediaDescriptor',
  full_name='microsoft.azure.media.graph.extensions.grpc.MediaDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timescale', full_name='microsoft.azure.media.graph.extensions.grpc.MediaDescriptor.timescale', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_frame_sample_format', full_name='microsoft.azure.media.graph.extensions.grpc.MediaDescriptor.video_frame_sample_format', index=1,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='media_sample_format', full_name='microsoft.azure.media.graph.extensions.grpc.MediaDescriptor.media_sample_format',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=61,
  serialized_end=226,
)


_VIDEOFRAMESAMPLEFORMAT = _descriptor.Descriptor(
  name='VideoFrameSampleFormat',
  full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoding', full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.encoding', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_format', full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.pixel_format', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.dimensions', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride', full_name='microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat.stride', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEOFRAMESAMPLEFORMAT_ENCODING,
    _VIDEOFRAMESAMPLEFORMAT_PIXELFORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=750,
)


_DIMENSIONS = _descriptor.Descriptor(
  name='Dimensions',
  full_name='microsoft.azure.media.graph.extensions.grpc.Dimensions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='microsoft.azure.media.graph.extensions.grpc.Dimensions.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='microsoft.azure.media.graph.extensions.grpc.Dimensions.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=752,
  serialized_end=795,
)


_CONTENTBYTES = _descriptor.Descriptor(
  name='ContentBytes',
  full_name='microsoft.azure.media.graph.extensions.grpc.ContentBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='microsoft.azure.media.graph.extensions.grpc.ContentBytes.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=797,
  serialized_end=826,
)


_CONTENTREFERENCE = _descriptor.Descriptor(
  name='ContentReference',
  full_name='microsoft.azure.media.graph.extensions.grpc.ContentReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_offset', full_name='microsoft.azure.media.graph.extensions.grpc.ContentReference.address_offset', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_bytes', full_name='microsoft.azure.media.graph.extensions.grpc.ContentReference.length_bytes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=828,
  serialized_end=892,
)


_CONTENTHANDLE = _descriptor.Descriptor(
  name='ContentHandle',
  full_name='microsoft.azure.media.graph.extensions.grpc.ContentHandle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle_name', full_name='microsoft.azure.media.graph.extensions.grpc.ContentHandle.handle_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=894,
  serialized_end=930,
)

_MEDIADESCRIPTOR.fields_by_name['video_frame_sample_format'].message_type = _VIDEOFRAMESAMPLEFORMAT
_MEDIADESCRIPTOR.oneofs_by_name['media_sample_format'].fields.append(
  _MEDIADESCRIPTOR.fields_by_name['video_frame_sample_format'])
_MEDIADESCRIPTOR.fields_by_name['video_frame_sample_format'].containing_oneof = _MEDIADESCRIPTOR.oneofs_by_name['media_sample_format']
_VIDEOFRAMESAMPLEFORMAT.fields_by_name['encoding'].enum_type = _VIDEOFRAMESAMPLEFORMAT_ENCODING
_VIDEOFRAMESAMPLEFORMAT.fields_by_name['pixel_format'].enum_type = _VIDEOFRAMESAMPLEFORMAT_PIXELFORMAT
_VIDEOFRAMESAMPLEFORMAT.fields_by_name['dimensions'].message_type = _DIMENSIONS
_VIDEOFRAMESAMPLEFORMAT_ENCODING.containing_type = _VIDEOFRAMESAMPLEFORMAT
_VIDEOFRAMESAMPLEFORMAT_PIXELFORMAT.containing_type = _VIDEOFRAMESAMPLEFORMAT
DESCRIPTOR.message_types_by_name['MediaDescriptor'] = _MEDIADESCRIPTOR
DESCRIPTOR.message_types_by_name['VideoFrameSampleFormat'] = _VIDEOFRAMESAMPLEFORMAT
DESCRIPTOR.message_types_by_name['Dimensions'] = _DIMENSIONS
DESCRIPTOR.message_types_by_name['ContentBytes'] = _CONTENTBYTES
DESCRIPTOR.message_types_by_name['ContentReference'] = _CONTENTREFERENCE
DESCRIPTOR.message_types_by_name['ContentHandle'] = _CONTENTHANDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MediaDescriptor = _reflection.GeneratedProtocolMessageType('MediaDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _MEDIADESCRIPTOR,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:microsoft.azure.media.graph.extensions.grpc.MediaDescriptor)
  })
_sym_db.RegisterMessage(MediaDescriptor)

VideoFrameSampleFormat = _reflection.GeneratedProtocolMessageType('VideoFrameSampleFormat', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOFRAMESAMPLEFORMAT,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:microsoft.azure.media.graph.extensions.grpc.VideoFrameSampleFormat)
  })
_sym_db.RegisterMessage(VideoFrameSampleFormat)

Dimensions = _reflection.GeneratedProtocolMessageType('Dimensions', (_message.Message,), {
  'DESCRIPTOR' : _DIMENSIONS,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:microsoft.azure.media.graph.extensions.grpc.Dimensions)
  })
_sym_db.RegisterMessage(Dimensions)

ContentBytes = _reflection.GeneratedProtocolMessageType('ContentBytes', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTBYTES,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:microsoft.azure.media.graph.extensions.grpc.ContentBytes)
  })
_sym_db.RegisterMessage(ContentBytes)

ContentReference = _reflection.GeneratedProtocolMessageType('ContentReference', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTREFERENCE,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:microsoft.azure.media.graph.extensions.grpc.ContentReference)
  })
_sym_db.RegisterMessage(ContentReference)

ContentHandle = _reflection.GeneratedProtocolMessageType('ContentHandle', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTHANDLE,
  '__module__' : 'media_pb2'
  # @@protoc_insertion_point(class_scope:microsoft.azure.media.graph.extensions.grpc.ContentHandle)
  })
_sym_db.RegisterMessage(ContentHandle)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
